/* ============================================================
   Circuito Verde · Base de datos de plantas
   Huerta agroecológica patagónica — fundamentada en INTA Bariloche
   (EEA Bariloche / ProHuerta Patagonia). Fuentes principales:
   · Calendario de siembra Bariloche 2017 (INTA)
   · Calendario hortícola sur de Río Negro / norte de Patagonia (INTA)
   · "Pautas para diseñar una huerta en la Patagonia cordillerana"
   · "Cinco opciones para ahuyentar las plagas de la huerta" (INTA Informa)
   · Cartilla "Control de plagas en la huerta" y biopreparados (INTA)
   · "Primer mapeo de huertas urbanas en Bariloche" (Repositorio INTA)
   · Río Negro Nutre (distancias de fruto, pimiento, zapallo, arveja)

   distancia (dist): cm recomendados entre planta y planta.
   funciones: comestible | repele | poliniza | benefico | nitrogeno | cobertura
   inv: conviene/necesita invernadero en Bariloche
   icon: arquetipo de dibujo a lápiz de color (ver app.js -> ICONS)
   ============================================================ */
const PLANTS = [
  /* ---------- HORTALIZAS DE HOJA ---------- */
  {id:"lechuga", nombre:"Lechuga", cientifico:"Lactuca sativa", familia:"Asteraceae", categoria:"Hortaliza de hoja", grupo:"Compuestas", funciones:["comestible"], dist:25, siembra:"Almácigo feb-jul y ago-sep, trasplante a los 30-40 días; directa primavera-verano", inv:false, color:"#7CB342", icon:"hoja", notas:"Clásico de huerta barilochense; bajo invernadero se cosecha casi todo el año. Se asocia con zanahoria y rabanito."},
  {id:"acelga", nombre:"Acelga", cientifico:"Beta vulgaris var. cicla", familia:"Amaranthaceae", categoria:"Hortaliza de hoja", grupo:"Quenopodiáceas", funciones:["comestible"], dist:25, siembra:"Almácigo o directa ago-mar, trasplante a los 30 días", inv:false, color:"#4CAF50", icon:"penca", notas:"Muy rústica y resistente al frío; una de las hojas más rendidoras en huerta patagónica."},
  {id:"espinaca", nombre:"Espinaca", cientifico:"Spinacia oleracea", familia:"Amaranthaceae", categoria:"Hortaliza de hoja", grupo:"Quenopodiáceas", funciones:["comestible"], dist:15, siembra:"Directa otoño (feb-abr) y fin de invierno; resiste heladas", inv:false, color:"#2E7D32", icon:"hoja", notas:"Cultivo de estación fría ideal para otoño-invierno bajo cobertura ligera."},
  {id:"rucula", nombre:"Rúcula", cientifico:"Eruca vesicaria sativa", familia:"Brassicaceae", categoria:"Hortaliza de hoja", grupo:"Brássicas", funciones:["comestible"], dist:15, siembra:"Directa prim-verano; bajo cubierta en frío; ciclo corto escalonado", inv:false, color:"#689F38", icon:"hoja", notas:"Crecimiento muy rápido; evaluada por INTA Bariloche en kits ProHuerta junto a lechuga y acelga."},
  {id:"kale", nombre:"Kale (col rizada)", cientifico:"Brassica oleracea var. sabellica", familia:"Brassicaceae", categoria:"Hortaliza de hoja", grupo:"Brássicas", funciones:["comestible"], dist:40, siembra:"Almácigo ago-ene, trasplante a los 30-40 días", inv:false, color:"#33691E", icon:"penca", notas:"Muy resistente a heladas; gana sabor tras la primera helada. Frecuente en huertas urbanas de Bariloche."},
  {id:"apio", nombre:"Apio", cientifico:"Apium graveolens", familia:"Apiaceae", categoria:"Hortaliza de hoja", grupo:"Apiáceas", funciones:["comestible"], dist:25, siembra:"Almácigo ago-oct, trasplante nov-dic", inv:false, color:"#9CCC65", icon:"penca", notas:"Buen compañero de puerro y repollo; prefiere suelos frescos y húmedos."},

  /* ---------- BRÁSSICAS DE CABEZA ---------- */
  {id:"repollo", nombre:"Repollo", cientifico:"Brassica oleracea var. capitata", familia:"Brassicaceae", categoria:"Hortaliza de hoja", grupo:"Brássicas", funciones:["comestible"], dist:50, siembra:"Almácigo ago-sep, trasplante nov; también dic para cosecha otoñal", inv:false, color:"#9CCC65", icon:"repollo", notas:"Asociar con capuchina y aromáticas para repeler la mariposa de la col."},
  {id:"brocoli", nombre:"Brócoli", cientifico:"Brassica oleracea var. italica", familia:"Brassicaceae", categoria:"Hortaliza de fruto", grupo:"Brássicas", funciones:["comestible"], dist:50, siembra:"Almácigo ago-sep, trasplante oct-nov", inv:false, color:"#388E3C", icon:"repollo", notas:"Cultivo de clima fresco que rinde bien en la cordillera; rebrota tras el corte central."},
  {id:"coliflor", nombre:"Coliflor", cientifico:"Brassica oleracea var. botrytis", familia:"Brassicaceae", categoria:"Hortaliza de fruto", grupo:"Brássicas", funciones:["comestible"], dist:50, siembra:"Almácigo ago-sep, trasplante oct-nov", inv:false, color:"#F0F4C3", icon:"repollo", notas:"Sensible al estrés térmico; preferir variedades de ciclo corto para la temporada corta patagónica."},

  /* ---------- RAÍCES ---------- */
  {id:"zanahoria", nombre:"Zanahoria", cientifico:"Daucus carota", familia:"Apiaceae", categoria:"Hortaliza de raíz", grupo:"Apiáceas", funciones:["comestible"], dist:8, siembra:"Directa sep-ene; raleo a 5-8 cm entre plantas", inv:false, color:"#EF6C00", icon:"raiz", notas:"Se asocia muy bien con cebolla y puerro: cada una repele la mosca de la otra."},
  {id:"remolacha", nombre:"Remolacha", cientifico:"Beta vulgaris var. conditiva", familia:"Amaranthaceae", categoria:"Hortaliza de raíz", grupo:"Quenopodiáceas", funciones:["comestible"], dist:10, siembra:"Directa sep-ene; raleo a 8-10 cm", inv:false, color:"#8E24AA", icon:"remolacha", notas:"Tubérculo frecuente en huertas urbanas de Bariloche; aprovechable también su hoja."},
  {id:"rabanito", nombre:"Rabanito", cientifico:"Raphanus sativus", familia:"Brassicaceae", categoria:"Hortaliza de raíz", grupo:"Brássicas", funciones:["comestible"], dist:5, siembra:"Directa todo el período libre de heladas; ciclo de 25-30 días", inv:false, color:"#E53935", icon:"raiz", notas:"El más rápido de la huerta; sirve para marcar surcos de zanahoria de germinación lenta."},
  {id:"nabo", nombre:"Nabo", cientifico:"Brassica rapa", familia:"Brassicaceae", categoria:"Hortaliza de raíz", grupo:"Brássicas", funciones:["comestible"], dist:12, siembra:"Directa fin de verano-otoño; resiste heladas suaves", inv:false, color:"#CE93D8", icon:"raiz", notas:"Cultivo rústico de otoño-invierno, muy adaptado al frío cordillerano."},
  {id:"papa", nombre:"Papa", cientifico:"Solanum tuberosum", familia:"Solanaceae", categoria:"Hortaliza de raíz", grupo:"Solanáceas", funciones:["comestible"], dist:35, siembra:"Plantación de tubérculos oct-nov (pasado el riesgo de helada fuerte)", inv:false, color:"#C0A16B", icon:"tuberculo", notas:"Tubérculo destacado en huertas barilochenses; aporcar para proteger los brotes de heladas tardías."},

  /* ---------- BULBOS (LILIÁCEAS) ---------- */
  {id:"ajo", nombre:"Ajo", cientifico:"Allium sativum", familia:"Amaryllidaceae", categoria:"Hortaliza de bulbo", grupo:"Liliáceas", funciones:["comestible","repele"], dist:10, siembra:"Plantación de dientes otoño-invierno (may-jul), cosecha fin de verano", inv:false, color:"#ECEFF1", icon:"ajo", notas:"Su aroma repele pulgones, moscas y mosquitos; base de biopreparados repelentes (INTA)."},
  {id:"cebolla", nombre:"Cebolla", cientifico:"Allium cepa", familia:"Amaryllidaceae", categoria:"Hortaliza de bulbo", grupo:"Liliáceas", funciones:["comestible","repele"], dist:12, siembra:"Almácigo jul-ago, trasplante oct; o directa", inv:false, color:"#D7A86E", icon:"bulbo", notas:"Asociada a zanahoria confunde a las moscas de ambas; insumo de biopreparados (INTA)."},
  {id:"puerro", nombre:"Puerro", cientifico:"Allium porrum", familia:"Amaryllidaceae", categoria:"Hortaliza de bulbo", grupo:"Liliáceas", funciones:["comestible","repele"], dist:12, siembra:"Almácigo ago-sep, trasplante nov-dic; aporcar", inv:false, color:"#AED581", icon:"bulbo", notas:"Muy rústico al frío; buen compañero de zanahoria y apio."},
  {id:"ciboulette", nombre:"Ciboulette (cebollín)", cientifico:"Allium schoenoprasum", familia:"Amaryllidaceae", categoria:"Aromática/Medicinal", grupo:"Liliáceas", funciones:["comestible","repele","poliniza"], dist:20, siembra:"Almácigo o división de matas en primavera; perenne", inv:false, color:"#BA68C8", icon:"bulbo", notas:"Sus flores violetas atraen polinizadores y su aroma aleja pulgones; perenne y muy resistente."},

  /* ---------- LEGUMBRES ---------- */
  {id:"arveja", nombre:"Arveja", cientifico:"Pisum sativum", familia:"Fabaceae", categoria:"Legumbre", grupo:"Leguminosas", funciones:["comestible","nitrogeno"], dist:8, siembra:"Directa fin de invierno-primavera (ago-oct); tolera frío", inv:false, color:"#7CB342", icon:"legumbre", notas:"Fija nitrógeno; frecuente en huertas urbanas de Bariloche. Hileras a ~50 cm, tutorada."},
  {id:"haba", nombre:"Haba", cientifico:"Vicia faba", familia:"Fabaceae", categoria:"Legumbre", grupo:"Leguminosas", funciones:["comestible","nitrogeno"], dist:20, siembra:"Directa otoño o fin de invierno; muy resistente a heladas", inv:false, color:"#9CCC65", icon:"legumbre", notas:"De las pocas que se siembran en otoño en la cordillera; fija nitrógeno y sirve de abono verde."},
  {id:"chaucha", nombre:"Chaucha (poroto)", cientifico:"Phaseolus vulgaris", familia:"Fabaceae", categoria:"Legumbre", grupo:"Leguminosas", funciones:["comestible","nitrogeno"], dist:10, siembra:"Directa nov-dic (pasadas las heladas); sensible al frío", inv:false, color:"#66BB6A", icon:"legumbre", notas:"Sensible a heladas: sembrar en pleno período libre de heladas o adelantar bajo invernadero."},

  /* ---------- SOLANÁCEAS / FRUTO (INVERNADERO) ---------- */
  {id:"tomate", nombre:"Tomate", cientifico:"Solanum lycopersicum", familia:"Solanaceae", categoria:"Hortaliza de fruto", grupo:"Solanáceas", funciones:["comestible"], dist:40, siembra:"Almácigo sep-oct, trasplante oct-nov bajo invernadero", inv:true, color:"#E4572E", icon:"tomate", notas:"En Bariloche solo da bajo invernadero; asociar con tagetes (nematodos), caléndula y albahaca."},
  {id:"pimiento", nombre:"Pimiento / morrón", cientifico:"Capsicum annuum", familia:"Solanaceae", categoria:"Hortaliza de fruto", grupo:"Solanáceas", funciones:["comestible"], dist:40, siembra:"Almácigo jul-ago, trasplante oct bajo invernadero", inv:true, color:"#D32F2F", icon:"pimiento", notas:"Requiere ~20°C y resguardo de heladas; en la cordillera solo prospera bajo cubierta (INTA)."},
  {id:"berenjena", nombre:"Berenjena", cientifico:"Solanum melongena", familia:"Solanaceae", categoria:"Hortaliza de fruto", grupo:"Solanáceas", funciones:["comestible"], dist:50, siembra:"Almácigo jul-ago, trasplante oct-nov bajo invernadero", inv:true, color:"#6A1B9A", icon:"pimiento", notas:"Muy termófila; INTA la lista entre los cultivos que en Bariloche solo se logran bajo invernadero."},
  {id:"aji", nombre:"Ají", cientifico:"Capsicum spp.", familia:"Solanaceae", categoria:"Hortaliza de fruto", grupo:"Solanáceas", funciones:["comestible","repele"], dist:40, siembra:"Almácigo jul-ago, trasplante oct bajo invernadero", inv:true, color:"#C62828", icon:"pimiento", notas:"Insumo de biopreparados repelentes (junto a ajo y ortiga, según INTA); solo bajo cubierta en la zona."},

  /* ---------- CUCURBITÁCEAS ---------- */
  {id:"zapallo", nombre:"Zapallo", cientifico:"Cucurbita maxima", familia:"Cucurbitaceae", categoria:"Hortaliza de fruto", grupo:"Cucurbitáceas", funciones:["comestible","poliniza"], dist:100, siembra:"Directa oct-nov; conviene adelantar en almácigo bajo cubierta", inv:true, color:"#F9A825", icon:"zapallo", notas:"Sensible a heladas; marco amplio (hasta 250-300 cm entre hileras). Capuchina contra la chinche del zapallo."},
  {id:"zapallito", nombre:"Zapallito", cientifico:"Cucurbita maxima var. zapallito", familia:"Cucurbitaceae", categoria:"Hortaliza de fruto", grupo:"Cucurbitáceas", funciones:["comestible","poliniza"], dist:80, siembra:"Almácigo oct bajo cubierta, trasplante nov; o directa nov-dic", inv:true, color:"#7CB342", icon:"zapallo", notas:"En la cordillera conviene invernadero o protección por su sensibilidad a las heladas."},
  {id:"pepino", nombre:"Pepino", cientifico:"Cucumis sativus", familia:"Cucurbitaceae", categoria:"Hortaliza de fruto", grupo:"Cucurbitáceas", funciones:["comestible","poliniza"], dist:40, siembra:"Almácigo oct, trasplante nov bajo invernadero", inv:true, color:"#558B2F", icon:"zapallo", notas:"INTA lo incluye entre las verduras que en Bariloche solo se obtienen bajo invernadero."},
  {id:"maiz", nombre:"Maíz", cientifico:"Zea mays", familia:"Poaceae", categoria:"Hortaliza de fruto", grupo:"Gramíneas", funciones:["comestible"], dist:30, siembra:"Directa nov (pasadas las heladas)", inv:false, color:"#F9A825", icon:"hoja", notas:"Entre los cultivos de huertas urbanas barilochenses; base de la milpa (maíz-poroto-zapallo)."},

  /* ---------- FRUTALES MENORES ---------- */
  {id:"frutilla", nombre:"Frutilla", cientifico:"Fragaria × ananassa", familia:"Rosaceae", categoria:"Frutal menor", grupo:"Rosáceas", funciones:["comestible","poliniza"], dist:30, siembra:"Plantación de plantines otoño o fin de invierno; perenne", inv:false, color:"#E53935", icon:"frutilla", notas:"Crece a campo en Bariloche; bajo invernadero adelanta y prolonga la cosecha. Sus flores atraen polinizadores."},
  {id:"ruibarbo", nombre:"Ruibarbo", cientifico:"Rheum rhabarbarum", familia:"Polygonaceae", categoria:"Frutal menor", grupo:"Poligonáceas", funciones:["comestible"], dist:90, siembra:"División de coronas en otoño/invierno; perenne longevo", inv:false, color:"#C2185B", icon:"penca", notas:"Perenne rústico ideal para clima frío; se cosechan los pecíolos (las hojas son tóxicas)."},

  /* ---------- AROMÁTICAS / MEDICINALES ---------- */
  {id:"perejil", nombre:"Perejil", cientifico:"Petroselinum crispum", familia:"Apiaceae", categoria:"Aromática/Medicinal", grupo:"Apiáceas", funciones:["comestible","benefico"], dist:15, siembra:"Directa o almácigo prim-verano; bienal", inv:false, color:"#388E3C", icon:"aromatica", notas:"En flor (2º año) atrae avispas y moscas benéficas; buen compañero del tomate."},
  {id:"cilantro", nombre:"Cilantro", cientifico:"Coriandrum sativum", familia:"Apiaceae", categoria:"Aromática/Medicinal", grupo:"Apiáceas", funciones:["comestible","benefico","poliniza"], dist:15, siembra:"Directa primavera; anual de ciclo corto", inv:false, color:"#7CB342", icon:"aromatica", notas:"Sus flores atraen sírfidos y avispitas predadoras de pulgones; se espiga rápido con calor."},
  {id:"albahaca", nombre:"Albahaca", cientifico:"Ocimum basilicum", familia:"Lamiaceae", categoria:"Aromática/Medicinal", grupo:"Labiadas/Lamiáceas", funciones:["comestible","repele","poliniza"], dist:25, siembra:"Almácigo oct bajo cubierta, trasplante nov-dic", inv:true, color:"#43A047", icon:"aromatica", notas:"INTA la incluye en surcos como repelente; en Bariloche prospera bajo invernadero junto al tomate."},
  {id:"oregano", nombre:"Orégano", cientifico:"Origanum vulgare", familia:"Lamiaceae", categoria:"Aromática/Medicinal", grupo:"Labiadas/Lamiáceas", funciones:["comestible","repele","poliniza"], dist:30, siembra:"Almácigo/división primavera; perenne", inv:false, color:"#558B2F", icon:"aromatica", notas:"INTA lo recomienda en el cerco vivo aromático; en flor atrae abejas y benéficos."},
  {id:"tomillo", nombre:"Tomillo", cientifico:"Thymus vulgaris", familia:"Lamiaceae", categoria:"Aromática/Medicinal", grupo:"Labiadas/Lamiáceas", funciones:["comestible","repele","poliniza"], dist:30, siembra:"Almácigo o esqueje primavera; perenne rústico", inv:false, color:"#7B9E54", icon:"aromatica", notas:"INTA lo ubica en los surcos como repelente; resistente al frío y la sequía."},
  {id:"romero", nombre:"Romero", cientifico:"Salvia rosmarinus", familia:"Lamiaceae", categoria:"Aromática/Medicinal", grupo:"Labiadas/Lamiáceas", funciones:["comestible","repele","poliniza"], dist:60, siembra:"Esqueje/plantín primavera; arbusto perenne", inv:false, color:"#5C6BC0", icon:"aromatica", notas:"INTA lo cita como base del cerco vivo repelente; sus flores son muy melíferas."},
  {id:"salvia", nombre:"Salvia", cientifico:"Salvia officinalis", familia:"Lamiaceae", categoria:"Aromática/Medicinal", grupo:"Labiadas/Lamiáceas", funciones:["comestible","repele","poliniza"], dist:50, siembra:"Almácigo/esqueje primavera; perenne", inv:false, color:"#9FA8DA", icon:"aromatica", notas:"Integra el cerco vivo aromático recomendado por INTA; repele la mariposa de la col."},
  {id:"menta", nombre:"Menta", cientifico:"Mentha spp.", familia:"Lamiaceae", categoria:"Aromática/Medicinal", grupo:"Labiadas/Lamiáceas", funciones:["comestible","repele","poliniza"], dist:30, siembra:"División de matas/estolones primavera; perenne invasivo", inv:false, color:"#26A69A", icon:"aromatica", notas:"INTA la coloca en los surcos como repelente; conviene contenerla en maceta por su agresividad."},
  {id:"melisa", nombre:"Melisa (toronjil)", cientifico:"Melissa officinalis", familia:"Lamiaceae", categoria:"Aromática/Medicinal", grupo:"Labiadas/Lamiáceas", funciones:["comestible","poliniza","benefico"], dist:30, siembra:"Almácigo/división primavera; perenne", inv:false, color:"#66BB6A", icon:"aromatica", notas:"Muy melífera (atrae abejas); rústica y de buena resistencia al frío."},
  {id:"eneldo", nombre:"Eneldo", cientifico:"Anethum graveolens", familia:"Apiaceae", categoria:"Aromática/Medicinal", grupo:"Apiáceas", funciones:["comestible","benefico","poliniza"], dist:20, siembra:"Directa primavera; anual", inv:false, color:"#9CCC65", icon:"aromatica", notas:"Flor en umbela que atrae sírfidos y avispas parasitoides; planta hospedera de mariquitas."},
  {id:"hinojo", nombre:"Hinojo", cientifico:"Foeniculum vulgare", familia:"Apiaceae", categoria:"Aromática/Medicinal", grupo:"Apiáceas", funciones:["comestible","benefico","poliniza"], dist:30, siembra:"Almácigo/directa primavera", inv:false, color:"#AEEA00", icon:"aromatica", notas:"Sus umbelas atraen muchos benéficos; conviene aislarlo porque inhibe a varios cultivos vecinos."},
  {id:"estragon", nombre:"Estragón", cientifico:"Artemisia dracunculus", familia:"Asteraceae", categoria:"Aromática/Medicinal", grupo:"Compuestas", funciones:["comestible","repele"], dist:40, siembra:"División/esqueje primavera; perenne", inv:false, color:"#689F38", icon:"aromatica", notas:"INTA lo menciona entre las aromáticas de surco con efecto repelente."},
  {id:"ajenjo", nombre:"Ajenjo", cientifico:"Artemisia absinthium", familia:"Asteraceae", categoria:"Aromática/Medicinal", grupo:"Compuestas", funciones:["repele"], dist:50, siembra:"Almácigo/división primavera; perenne", inv:false, color:"#9E9D24", icon:"aromatica", notas:"INTA: ahuyenta la mosca blanca; ubicarlo en el cerco vivo, lejos de cultivos sensibles (alelopático)."},
  {id:"ruda", nombre:"Ruda", cientifico:"Ruta graveolens", familia:"Rutaceae", categoria:"Aromática/Medicinal", grupo:"Rutáceas", funciones:["repele"], dist:50, siembra:"Almácigo/esqueje primavera; perenne", inv:false, color:"#7CB342", icon:"aromatica", notas:"INTA la señala como una de las más repelentes: controla piojos, pulgones, ácaros, babosas y mosca blanca."},
  {id:"ortiga", nombre:"Ortiga", cientifico:"Urtica dioica", familia:"Urticaceae", categoria:"Aromática/Medicinal", grupo:"Urticáceas", funciones:["repele","benefico"], dist:40, siembra:"Espontánea/almácigo primavera; perenne", inv:false, color:"#33691E", icon:"hoja", notas:"Base del purín de ortiga (INTA) como fortificante y repelente; refugio de insectos benéficos."},
  {id:"consuelda", nombre:"Consuelda", cientifico:"Symphytum officinale", familia:"Boraginaceae", categoria:"Aromática/Medicinal", grupo:"Borragináceas", funciones:["poliniza","cobertura"], dist:60, siembra:"División de raíz primavera/otoño; perenne", inv:false, color:"#8E24AA", icon:"flor", notas:"Acumuladora de potasio para purín fertilizante; sus flores atraen abejorros."},

  /* ---------- FLORES: REPELENTES Y ATRACTORAS ---------- */
  {id:"lavanda", nombre:"Lavanda", cientifico:"Lavandula angustifolia", familia:"Lamiaceae", categoria:"Flor", grupo:"Labiadas/Lamiáceas", funciones:["repele","poliniza"], dist:50, siembra:"Esqueje/plantín primavera; arbusto perenne", inv:false, color:"#7E57C2", icon:"lavanda", notas:"INTA la cita como pilar del cerco vivo; repele pulgones/polillas y es muy atractiva para abejas."},
  {id:"tagete", nombre:"Tagetes (copete / clavel de China)", cientifico:"Tagetes patula", familia:"Asteraceae", categoria:"Flor", grupo:"Compuestas", funciones:["repele","poliniza","benefico"], dist:25, siembra:"Almácigo sep-oct, trasplante nov; o directa primavera", inv:false, color:"#FB8C00", icon:"flor", notas:"INTA: plantado con tomates ahuyenta los nematodos del suelo y la mosca blanca."},
  {id:"calendula", nombre:"Caléndula", cientifico:"Calendula officinalis", familia:"Asteraceae", categoria:"Flor", grupo:"Compuestas", funciones:["repele","poliniza","benefico","comestible"], dist:30, siembra:"Almácigo/directa otoño o primavera; resiembra sola", inv:false, color:"#FFB300", icon:"flor", notas:"INTA: repele pulgones, chinches y gusanos; asociar con tomate, pimiento y berenjena. Pétalos comestibles."},
  {id:"capuchina", nombre:"Capuchina (taco de reina)", cientifico:"Tropaeolum majus", familia:"Tropaeolaceae", categoria:"Flor", grupo:"Tropeoláceas", funciones:["comestible","repele","benefico","poliniza"], dist:30, siembra:"Directa primavera (sep-nov)", inv:false, color:"#F4511E", icon:"flor", notas:"INTA: ahuyenta la chinche del zapallo y, como planta trampa de pulgones, atrae avispas predadoras. Flores y hojas comestibles."},
  {id:"borraja", nombre:"Borraja", cientifico:"Borago officinalis", familia:"Boraginaceae", categoria:"Flor", grupo:"Borragináceas", funciones:["comestible","poliniza","benefico"], dist:30, siembra:"Directa primavera; anual que resiembra", inv:false, color:"#3F51B5", icon:"flor", notas:"Una de las flores más atractivas para abejas y abejorros; mejora el cuajado del tomate vecino."},
  {id:"cosmos", nombre:"Cosmos", cientifico:"Cosmos bipinnatus", familia:"Asteraceae", categoria:"Flor", grupo:"Compuestas", funciones:["poliniza","benefico"], dist:30, siembra:"Almácigo/directa primavera; anual", inv:false, color:"#EC407A", icon:"margarita", notas:"Florece abundante; atrae sírfidos, avispas benéficas y abejas a la huerta."},
  {id:"alyssum", nombre:"Alyssum (canastillo de oro)", cientifico:"Lobularia maritima", familia:"Brassicaceae", categoria:"Flor", grupo:"Brássicas", funciones:["benefico","poliniza","cobertura"], dist:15, siembra:"Directa/almácigo primavera; tapizante anual", inv:false, color:"#F8BBD0", icon:"flor", notas:"Imán de sírfidos y avispitas parasitoides de pulgones; tapiza bordes de cantero."},
  {id:"girasol", nombre:"Girasol", cientifico:"Helianthus annuus", familia:"Asteraceae", categoria:"Flor", grupo:"Compuestas", funciones:["comestible","poliniza","benefico"], dist:40, siembra:"Directa nov (pasadas las heladas)", inv:false, color:"#FDD835", icon:"girasol", notas:"Citado entre los cultivos de huertas urbanas de Bariloche; atrae abejas y sirve de tutor vivo."},
  {id:"manzanilla", nombre:"Manzanilla", cientifico:"Matricaria chamomilla", familia:"Asteraceae", categoria:"Flor", grupo:"Compuestas", funciones:["repele","benefico","poliniza","comestible"], dist:20, siembra:"Directa otoño o primavera; anual que resiembra", inv:false, color:"#FFF176", icon:"margarita", notas:"Integra el cerco vivo de INTA; atrae benéficos y se usa en infusión antifúngica para la huerta."},

  /* ---------- ABONOS VERDES / COBERTURA ---------- */
  {id:"phacelia", nombre:"Facelia", cientifico:"Phacelia tanacetifolia", familia:"Boraginaceae", categoria:"Abono verde/Cobertura", grupo:"Borragináceas", funciones:["poliniza","benefico","cobertura"], dist:10, siembra:"Al voleo en primavera/verano; ciclo corto", inv:false, color:"#7986CB", icon:"flor", notas:"Uno de los mejores imanes de abejas y sírfidos; excelente abono verde y supresor de malezas."},
  {id:"trebol", nombre:"Trébol blanco", cientifico:"Trifolium repens", familia:"Fabaceae", categoria:"Abono verde/Cobertura", grupo:"Leguminosas", funciones:["nitrogeno","cobertura","poliniza"], dist:10, siembra:"Al voleo otoño o primavera; perenne", inv:false, color:"#9CCC65", icon:"flor", notas:"Fija nitrógeno y cubre el suelo entre canteros; sus flores atraen abejas."},
  {id:"mostaza", nombre:"Mostaza", cientifico:"Sinapis alba", familia:"Brassicaceae", categoria:"Abono verde/Cobertura", grupo:"Brássicas", funciones:["cobertura","poliniza","repele"], dist:10, siembra:"Al voleo otoño o primavera; ciclo corto", inv:false, color:"#FFEB3B", icon:"flor", notas:"Abono verde de crecimiento rápido con efecto biofumigante sobre nematodos y hongos del suelo."},
  {id:"vicia", nombre:"Vicia", cientifico:"Vicia sativa", familia:"Fabaceae", categoria:"Abono verde/Cobertura", grupo:"Leguminosas", funciones:["nitrogeno","cobertura"], dist:10, siembra:"Al voleo otoño; se incorpora en primavera", inv:false, color:"#7E57C2", icon:"flor", notas:"Leguminosa de cobertura invernal; fija nitrógeno y suele asociarse con avena."},
  {id:"avena", nombre:"Avena", cientifico:"Avena sativa", familia:"Poaceae", categoria:"Abono verde/Cobertura", grupo:"Gramíneas", funciones:["cobertura"], dist:5, siembra:"Al voleo otoño; mejora estructura del suelo", inv:false, color:"#C0CA33", icon:"hoja", notas:"Abono verde gramíneo que protege el suelo en invierno; se combina con vicia (carbono + nitrógeno)."},
];
